// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCioZ7EG-HOBMuQN8jb2e4zV8NFO6Nzpuw',
//     appId: '1:83993137999:web:55fd3d8d7e4f01916a6b3a',
//     messagingSenderId: '83993137999',
//     projectId: 'samx-bfa29',
//     authDomain: 'samx-bfa29.firebaseapp.com',
//     storageBucket: 'samx-bfa29.appspot.com',
//     measurementId: 'G-N3B42MHV3J',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCP0O6KvBxSGHrV7muIvPF4jw0idwyIVNA',
//     appId: '1:83993137999:android:11fe7c2920f04f686a6b3a',
//     messagingSenderId: '83993137999',
//     projectId: 'samx-bfa29',
//     storageBucket: 'samx-bfa29.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDfxZtJE0zSh2955cSt-Dsa4Y1FBdju_gg',
//     appId: '1:83993137999:ios:b60959b7e96968bf6a6b3a',
//     messagingSenderId: '83993137999',
//     projectId: 'samx-bfa29',
//     storageBucket: 'samx-bfa29.appspot.com',
//     iosBundleId: 'com.saman.insuranse',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDfxZtJE0zSh2955cSt-Dsa4Y1FBdju_gg',
//     appId: '1:83993137999:ios:205e77f67ee6bc6e6a6b3a',
//     messagingSenderId: '83993137999',
//     projectId: 'samx-bfa29',
//     storageBucket: 'samx-bfa29.appspot.com',
//     iosBundleId: 'com.saman.singlewindow',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCioZ7EG-HOBMuQN8jb2e4zV8NFO6Nzpuw',
//     appId: '1:83993137999:web:431f61640959297b6a6b3a',
//     messagingSenderId: '83993137999',
//     projectId: 'samx-bfa29',
//     authDomain: 'samx-bfa29.firebaseapp.com',
//     storageBucket: 'samx-bfa29.appspot.com',
//     measurementId: 'G-HJH3JK7Y9N',
//   );
// }
